name: lab7

on:
  push:
    branches:
      - '**lab7**'
  pull_request:
    branches:
      - lab7

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

      fail-fast: false

    steps:

      - name: setup
        run: |
          echo "${HOME}/opt/conda/bin" >> $GITHUB_PATH
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REF
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.head }}
          echo ${{ github.event.pull_request.user.login }}
          echo ${{ github.event.pull_request.head.user.login }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: dependency (ubuntu)
        if: matrix.os != 'macos-latest'
        run: |
          sudo apt-get -qy install python3
          sudo apt-get -qy install golang-go
      - name: grade
        run: |
          username=$( [ -z "${{ github.event.pull_request.user.login }}" ] && echo $GITHUB_REPOSITORY | cut -d '/' -f 1 || echo ${{ github.event.pull_request.user.login }})
          echo "cd lab7/$username"
          cd lab7/$username
          bash ../validate.sh